name: ci-pr

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: abinnovision/actions@run-commitlint-v1